import type { AnalysisReport } from '../types/analysis';
import type { ReportPriceChartFixtures } from '../components/report/ReportPriceChart';

export const previewReport: AnalysisReport = {
  meta: {
    queryId: 'preview-q1',
    stockCode: 'NVDA',
    stockName: 'NVIDIA',
    reportType: 'full',
    createdAt: '2026-03-28T21:35:00+08:00',
  },
  summary: {
    analysisSummary: '等待回踩确认',
    operationAdvice: '观望',
    trendPrediction: '看多',
    sentimentScore: 78,
  },
  details: {
    standardReport: {
      summaryPanel: {
        stock: 'NVIDIA',
        ticker: 'NVDA',
        score: 78,
        currentPrice: '125.30',
        priceLabel: 'Analysis Price',
        priceBasis: 'Intraday snapshot',
        priceBasisDetail: 'Captured from a market snapshot during the current session, not streaming tick-by-tick data.',
        changeAmount: '2.30',
        changePct: '1.87%',
        marketTime: '2026-03-28 09:35:00 EDT',
        marketSessionDate: '2026-03-28',
        sessionLabel: '常规交易时段',
        referenceSession: '2026-03-28 regular session',
        snapshotTime: '2026-03-28 09:35:00 EDT',
        reportGeneratedAt: '2026-03-28 21:35:00 CST',
        priceContextNote: 'Entry, stop, target, support and resistance are anchored to the same intraday snapshot shown above.',
        operationAdvice: '观望',
        trendPrediction: '看多',
        oneSentence: '等待回踩确认后再考虑加仓',
        timeSensitivity: '3日内',
      },
      market: {
        regularMetrics: {
          price: 125.3,
          prevClose: 123.0,
          changeAmount: 2.3,
          changePct: 1.87,
          open: 123.5,
          high: 126.2,
          low: 122.9,
          close: 124.0,
          volume: 45678900,
          amount: 5723456789,
        },
        displayFields: [
          { label: 'Analysis Price', value: '125.30' },
          { label: 'Prev Close', value: '123.00' },
          { label: 'Session Open', value: '123.50' },
          { label: 'Session High', value: '126.20' },
          { label: 'Session Low', value: '122.90' },
          { label: 'Change', value: '2.30' },
          { label: 'Change %', value: '1.87%' },
          { label: 'Volume', value: '45.68M' },
          { label: 'Turnover', value: '5.72B' },
        ],
        consistencyWarnings: ['常规时段多源涨跌口径存在较大偏差，已优先采用当前价与昨收重算结果'],
      },
      tableSections: {
        market: {
          title: '行情表',
          fields: [
            { label: 'Analysis Price', value: '125.30' },
            { label: 'Change %', value: '1.87%' },
          ],
        },
        technical: {
          title: '技术面表',
          fields: [
            { label: 'MA20', value: '120.99', source: 'FMP API', status: '已就绪' },
            { label: 'RSI14', value: '56.78', source: 'FMP API', status: '已就绪' },
          ],
        },
        fundamental: {
          title: '基本面表',
          fields: [
            { label: '总市值(最新值)', value: '1234.00亿', source: 'FMP', status: '最新值' },
            { label: '市盈率(TTM)', value: '28.10', source: 'FMP', status: 'TTM' },
          ],
        },
        earnings: {
          title: '财报表',
          fields: [
            { label: '财报趋势摘要(最新季度)', value: '最新季度同比口径：营收与利润同向改善。', source: 'FMP Statements', status: '最新季度' },
            { label: '营收同比增速(最新季度同比)', value: '12.00%', source: 'FMP Statements', status: '最新季度同比' },
          ],
        },
      },
      visualBlocks: {
        score: { value: 78, max: 100 },
        trendStrength: { value: 72, max: 100, label: '多头排列' },
        pricePosition: {
          currentPrice: 125.3,
          ma20: 120.99,
          ma60: 118.88,
          distanceToMa20Pct: 3.56,
          distanceToMa60Pct: 5.40,
          vsMa20: '上方',
          vsMa60: '上方',
        },
        riskOpportunity: {
          positiveCount: 2,
          riskCount: 1,
          latestNewsCount: 1,
        },
      },
      decisionContext: {
        shortTermView: '短线技术偏弱，等待均线重新收敛。',
        compositeView: '基本面仍有支撑，综合建议以观望为主。',
        adjustmentReason: 'MA5/10/20/60 已补齐，并保留基本面缓冲。',
        changeReason: '技术指标补齐导致',
        previousScore: '81',
        scoreChange: '-3',
        scoreBreakdown: [
          { label: '技术分', score: 38, note: '均线结构偏空', tone: 'danger' },
          { label: '基本面分', score: 72, note: '现金流健康', tone: 'success' },
        ],
      },
      decisionPanel: {
        setupType: '回踩买点',
        confidence: '中高',
        keyAction: '优先等待回踩 MA20 一带出现承接，再考虑分批试仓。',
        analysisPrice: 125.3,
        support: '120.10（近期支撑 / MA 簇）',
        supportLevel: 120.1,
        resistance: '132.00（前高 / 压力位）',
        resistanceLevel: 132,
        idealEntry: '120-121',
        idealEntryCenter: 120.5,
        backupEntry: '118',
        backupEntryCenter: 118,
        stopLoss: '115',
        stopLossLevel: 115,
        target: '132',
        targetOne: '132',
        targetOneLevel: 132,
        targetTwo: '138',
        targetTwoLevel: 138,
        targetZone: '132-138',
        stopReason: '跌破最近支撑后，做多结构被技术性否定。',
        targetReason: '优先锚定前高与更强压力位。',
        marketStructure: 'MA5/10/20/60 = 123.4 / 122.8 / 120.9 / 118.8',
        atrProxy: 2.4,
        positionSizing: '分批试仓',
        buildStrategy: '等待回踩后分两笔建立底仓',
        riskControlStrategy: '放量跌破支撑位则收缩仓位',
        noPositionAdvice: '等待回踩确认后分批试仓',
        holderAdvice: '量价结构未破坏前继续跟踪',
        executionReminders: ['若放量跌破支撑位，需立即收缩仓位'],
      },
      reasonLayer: {
        coreReasons: ['基本面仍有支撑，综合建议以观望为主。', '短线技术偏弱，等待均线重新收敛。', '数据中心需求回暖'],
        topRisk: '估值仍偏高',
        topCatalyst: '数据中心需求回暖',
        latestKeyUpdate: '公司发布新品并强化生态合作',
        sentimentSummary: '情绪边际回暖',
        checklistSummary: '仍有1项执行条件待确认，建议继续观察量价配合。',
        newsValueTier: '高价值优先',
      },
      highlights: {
        positiveCatalysts: ['数据中心需求回暖', 'AI 订单延续'],
        riskAlerts: ['估值仍偏高'],
        latestNews: ['公司发布新品并强化生态合作'],
        newsValueGrade: '高价值优先',
        sentimentSummary: '情绪边际回暖',
        earningsOutlook: '盈利预期改善',
        bullishFactors: ['数据中心需求回暖', 'AI 订单延续'],
        bearishFactors: ['估值仍偏高', '上方前高压力仍在'],
        neutralFactors: ['暂无新的公司级催化，短线更依赖技术结构确认。'],
        socialSynthesis: '综合 Reddit / X / Polymarket 的讨论语义：discussion appears elevated，tone is mixed，当前关注点集中在 AI 需求与突破确认。该卡片为 LLM 综合讨论摘要，不等同于已核实硬新闻。',
        socialAttention: 'discussion appears elevated',
        socialTone: 'mixed',
        socialNarrativeFocus: 'AI 需求与突破确认',
        socialSources: ['Reddit', 'X / Twitter'],
      },
      coverageNotes: {
        dataSources: ['FMP API', 'FMP Statements', '本地派生'],
        coverageGaps: ['VWAP'],
        conflictNotes: ['ROE(TTM待复核)：TTM待复核'],
        missingFieldNotes: ['VWAP：字段待接入'],
        methodNotes: ['标准技术指标优先使用 API 原始值。'],
      },
      battlePlanCompact: {
        cards: [
          { label: '理想买入点', value: '120-121', tone: 'buy' },
          { label: '止损位', value: '115', tone: 'risk' },
          { label: '目标位', value: '132', tone: 'target' },
          { label: '仓位建议', value: '分批试仓', tone: 'position' },
        ],
        notes: [
          { label: '建仓策略', value: '等待回踩后分两笔建立底仓', tone: 'note' },
        ],
        warnings: ['若放量跌破支撑位，需立即收缩仓位'],
      },
      checklistItems: [
        { status: 'warn', icon: '⚠️', text: '等待回踩确认' },
        { status: 'pass', icon: '✅', text: '量价结构未破坏' },
      ],
    },
  },
};

export const previewChartFixtures: ReportPriceChartFixtures = {
  minute1: {
    source: 'Preview intraday feed',
    data: [
      { time: '2026-03-28T09:30:00-04:00', open: 124.9, high: 125.6, low: 124.7, close: 125.3, volume: 1200 },
      { time: '2026-03-28T09:35:00-04:00', open: 125.3, high: 125.9, low: 125.1, close: 125.6, volume: 1600 },
      { time: '2026-03-28T09:40:00-04:00', open: 125.6, high: 126.0, low: 125.2, close: 125.4, volume: 1500 },
      { time: '2026-03-28T09:45:00-04:00', open: 125.4, high: 126.2, low: 125.3, close: 125.9, volume: 1800 },
      { time: '2026-03-28T09:50:00-04:00', open: 125.9, high: 126.1, low: 125.4, close: 125.7, volume: 1700 },
    ],
  },
  minute5: {
    source: 'Preview daily feed',
    data: [
      { date: '2026-03-24', open: 120, high: 123, low: 119, close: 122, volume: 10 },
      { date: '2026-03-25', open: 122, high: 124, low: 121, close: 123, volume: 11 },
      { date: '2026-03-26', open: 123, high: 125, low: 122, close: 124, volume: 12 },
      { date: '2026-03-27', open: 124, high: 126, low: 123, close: 125.3, volume: 13 },
    ],
  },
  daily: {
    source: 'Preview daily feed',
    data: [
      { date: '2026-01-08', open: 111, high: 115, low: 109, close: 114, volume: 21 },
      { date: '2026-02-08', open: 116, high: 119, low: 113, close: 117, volume: 24 },
      { date: '2026-03-08', open: 118, high: 126, low: 117, close: 125.3, volume: 27 },
    ],
  },
  yearly: {
    source: 'Preview daily feed',
    data: [
      { date: '2025-06-28', open: 96, high: 102, low: 94, close: 101, volume: 28 },
      { date: '2025-09-28', open: 103, high: 111, low: 100, close: 109, volume: 30 },
      { date: '2025-12-28', open: 111, high: 118, low: 108, close: 116, volume: 34 },
      { date: '2026-03-28', open: 118, high: 126, low: 117, close: 125.3, volume: 38 },
    ],
  },
  weekly: {
    source: 'Preview weekly feed',
    data: [
      { date: '2026-03-06', open: 117, high: 120, low: 114, close: 118, volume: 42 },
      { date: '2026-03-13', open: 118, high: 122, low: 116, close: 121, volume: 45 },
      { date: '2026-03-20', open: 121, high: 124, low: 118, close: 123, volume: 48 },
      { date: '2026-03-27', open: 123, high: 126.2, low: 122.9, close: 125.3, volume: 52 },
    ],
  },
  monthly: {
    source: 'Preview monthly feed',
    data: [
      { date: '2025-12-01', open: 98, high: 108, low: 95, close: 106, volume: 62 },
      { date: '2026-01-01', open: 106, high: 116, low: 104, close: 113, volume: 68 },
      { date: '2026-02-01', open: 113, high: 121, low: 111, close: 118, volume: 72 },
      { date: '2026-03-01', open: 118, high: 126.2, low: 117, close: 125.3, volume: 76 },
    ],
  },
};
