import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    loadingNewsBody: '正在整理最新资讯条目，请稍候。',
    noNews: '暂无相关资讯',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    traceabilityNote: '原始结果和上下文快照仅用于追溯，不会改变页面上已经渲染的建议与结论区块。',
    fullReport: '完整研究报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    markdownRawHint: '此处展示原始 Markdown 报告，适合完整阅读与导出。',
    markdownLoadingBody: '正在拉取 Markdown 内容，请稍候。',
    markdownErrorBody: '可以关闭抽屉后重新打开，或稍后再试。',
    coverageAuditTitle: '覆盖与缺失字段审计',
    coverageAuditBody: '保留完整缺失字段，并按原因归类，便于覆盖审计与后续数据接入规划。',
    missingFieldsTotal: '缺失字段总数',
    noMissingFields: '当前未识别到缺失字段。',
    missingIntegratedUnavailable: '已接入但本次记录未返回',
    missingNotIntegratedYet: '字段待接入',
    missingSourceNotProvided: '当前数据源未提供',
    missingNotApplicable: '当前市场/会话不适用',
    missingOther: '其他缺失原因',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    loadingNewsBody: 'Refreshing the latest news items for this record. Please wait a moment.',
    noNews: 'No related news',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    traceabilityNote: 'Raw result and snapshot are shown for traceability only and do not change the rendered recommendation blocks.',
    fullReport: 'Full Research Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    markdownRawHint: 'This drawer shows the raw Markdown report for full reading and export.',
    markdownLoadingBody: 'Fetching markdown content. Please wait.',
    markdownErrorBody: 'Close and reopen the drawer, or try again later.',
    coverageAuditTitle: 'Coverage and missing-field audit',
    coverageAuditBody: 'Keep all missing fields visible and classify causes for coverage audit and integration planning.',
    missingFieldsTotal: 'Total missing fields',
    noMissingFields: 'No missing fields were identified.',
    missingIntegratedUnavailable: 'Integrated but unavailable',
    missingNotIntegratedYet: 'Not integrated yet',
    missingSourceNotProvided: 'Not provided by current source',
    missingNotApplicable: 'Not applicable for this market/session',
    missingOther: 'Other missing reasons',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
